import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Posts',
  description: 'Generated by create next app',
}

export default async function UserProfileLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <div className="bg-black text-white">
      {children}
    </div>
  )
}
